### ISSUE TITLE
Some are white……

### ISSUE THREAD

**Issue by MicroSun-MS** [Tim-Fang/Dark-Aerfaying-Theme#1]
![image](https://user-images.githubusercontent.com/83148843/118799490-5d6c8200-b8d1-11eb-9719-3a39ead5a822.png)
![image](https://user-images.githubusercontent.com/83148843/118799502-5fcedc00-b8d1-11eb-8e5d-aa36ff821476.png)
![image](https://user-images.githubusercontent.com/83148843/118799693-9b69a600-b8d1-11eb-98d8-fe964b7c1c20.png)
![g57T0K.gif](https://z3.ax1x.com/2021/05/19/g57T0K.gif)
[![2ppT0g.png](https://z3.ax1x.com/2021/05/26/2ppT0g.png)](https://imgtu.com/i/2ppT0g)
对比度不明显，还有勋章镶嵌进去了

**Comment by 3001hbd** [comment]
（貌似不看

**Comment by MicroSun-MS** [comment]
> （貌似不看
做编辑的时候必须得看
![](https://z3.ax1x.com/2021/05/19/g57T0K.gif)

**Comment by 3001hbd** [comment]
> > （小金卡·德
> > ![](https://camo.githubusercontent.com/7c2b4a24175bff782ee658f449c53140907569df991518b01ce0bea3e631fd86/68747470733a2f2f7a332e617831782e636f6d2f323032312f30352f31392f67353754304b2e676966)

（直接去主页催（？）

**Comment by MicroSun-MS** [comment]
催过了额啊

**Comment by MicroSun-MS** [comment]
> > > （小金卡·德
> > > ![](https://camo.githubusercontent.com/7c2b4a24175bff782ee658f449c53140907569df991518b01ce0bea3e631fd86/68747470733a2f2f7a332e617831782e636f6d2f323032312f30352f31392f67353754304b2e676966)
> 
> （直接去主页催（？）

啊啊啊催更过了不理啊

**Comment by wrj2009** [comment]
> 对比度不明显，还有勋章镶嵌进去了

那是A营的特性

**Comment by wrj2009** [comment]
Pull request #3 已修复😝
@MicroSun-MS @3001hbd
