### ISSUE TITLE
奥的灰烬右上角有个#

### ISSUE THREAD

**Issue by 3001hbd** [Tim-Fang/Dark-Aerfaying-Theme#11]
![image](https://user-images.githubusercontent.com/62171462/130028637-61bf6844-79e8-4ecc-9314-1d9fba5d19fc.png)  
如图所示，奥的灰烬右上方也会有个#

**Comment by threesix-aerfaying** [comment]
这是Tim-Fang佬特意制作的一个功能，可以获取此评论的ID（每个评论都有ID），由于奥灰随机推荐没有没有ID，所以就只能看见ID前面的标识符 **#** 了
