### ISSUE TITLE
New!!!!

### ISSUE THREAD

**Issue by Tim-Fang** [Tim-Fang/Dark-Aerfaying-Theme#7]
![图片](https://user-images.githubusercontent.com/60050973/125871558-4fe9d991-e074-4f85-b6c4-64042961196b.png)
测试中功能

**Comment by HardJerry** [comment]
怎么使用？为什么我这里没有qwq

**Comment by Tim-Fang** [comment]
> 怎么使用？为什么我这里没有qwq

显然 这个功能非常敏感 所以我单独拆出来做了个脚本 并且混淆了代码  
http://timfang.xyz:9999/files/admintools-min.js  
哦对了 这里面大部分功能还没有完全写好 也有很多坑留着  
也别想着逆向了
